/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notifikasi`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ScreenErrorFallback`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/route-error-boundary`; params?: Router.UnknownInputParams; } | { pathname: `/../../../packages/shared/src/presence-location`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/background-location-task`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/background-location`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/background-location-prefs`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useBackgroundLocation`; params?: Router.UnknownInputParams; } | { pathname: `/../../../tests/presence-location.test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pekerjaan` | `/pekerjaan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tiket` | `/tiket`; params?: Router.UnknownInputParams; } | { pathname: `/pekerjaan/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/notifikasi`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ScreenErrorFallback`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/route-error-boundary`; params?: Router.UnknownOutputParams; } | { pathname: `/../../../packages/shared/src/presence-location`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/background-location-task`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/background-location`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/background-location-prefs`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useBackgroundLocation`; params?: Router.UnknownOutputParams; } | { pathname: `/../../../tests/presence-location.test`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pekerjaan` | `/pekerjaan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tiket` | `/tiket`; params?: Router.UnknownOutputParams; } | { pathname: `/pekerjaan/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/notifikasi${`?${string}` | `#${string}` | ''}` | `/../components/ScreenErrorFallback${`?${string}` | `#${string}` | ''}` | `/../lib/route-error-boundary${`?${string}` | `#${string}` | ''}` | `/../../../packages/shared/src/presence-location${`?${string}` | `#${string}` | ''}` | `/../lib/background-location-task${`?${string}` | `#${string}` | ''}` | `/../lib/background-location${`?${string}` | `#${string}` | ''}` | `/../lib/background-location-prefs${`?${string}` | `#${string}` | ''}` | `/../hooks/useBackgroundLocation${`?${string}` | `#${string}` | ''}` | `/../../../tests/presence-location.test${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pekerjaan${`?${string}` | `#${string}` | ''}` | `/pekerjaan${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profil${`?${string}` | `#${string}` | ''}` | `/profil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tiket${`?${string}` | `#${string}` | ''}` | `/tiket${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notifikasi`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ScreenErrorFallback`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/route-error-boundary`; params?: Router.UnknownInputParams; } | { pathname: `/../../../packages/shared/src/presence-location`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/background-location-task`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/background-location`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/background-location-prefs`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useBackgroundLocation`; params?: Router.UnknownInputParams; } | { pathname: `/../../../tests/presence-location.test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pekerjaan` | `/pekerjaan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profil` | `/profil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tiket` | `/tiket`; params?: Router.UnknownInputParams; } | `/pekerjaan/${Router.SingleRoutePart<T>}` | { pathname: `/pekerjaan/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
