import type { MasterFasePekerjaan } from './types'

/**
 * Fallback master fase (mirror seeder APIAMIS) bila endpoint kosong/gagal.
 * Digunakan agar Auto-Fill Rencana tetap jalan di app lapangan.
 */
export const DEFAULT_MASTER_FASES: MasterFasePekerjaan[] = [
  // SANITASI
  {
    id: -101,
    jenis_proyek: 'sanitasi',
    kode_fase: 'persiapan',
    nama_fase: 'Pekerjaan Persiapan',
    prioritas: 0,
    overlap_persen: 0,
    durasi_faktor: 1,
    keywords: ['persiapan', 'mobilisasi', 'bouwplank', 'pengukuran'],
    is_active: true,
  },
  {
    id: -102,
    jenis_proyek: 'sanitasi',
    kode_fase: 'tanah',
    nama_fase: 'Pekerjaan Tanah',
    prioritas: 1,
    overlap_persen: 0,
    durasi_faktor: 1,
    keywords: ['tanah', 'galian', 'urugan', 'timbunan'],
    is_active: true,
  },
  {
    id: -103,
    jenis_proyek: 'sanitasi',
    kode_fase: 'bangunan_pengolah',
    nama_fase: 'Bangunan Pengolah',
    prioritas: 2,
    overlap_persen: 20,
    durasi_faktor: 1.2,
    keywords: [
      'stp',
      'biofilter',
      'septik',
      'bak',
      'sump pit',
      'grease trap',
      'sumur resapan',
      'struktur risha',
      'beton',
      'bekisting',
    ],
    is_active: true,
  },
  {
    id: -104,
    jenis_proyek: 'sanitasi',
    kode_fase: 'perpipaan_dalam',
    nama_fase: 'Perpipaan Dalam Gedung',
    prioritas: 3,
    overlap_persen: 25,
    durasi_faktor: 1,
    keywords: ['perpipaan dalam', 'pipa pvc', 'pipa galvanis', 'pipa ppr', 'pipa hdpe'],
    is_active: true,
  },
  {
    id: -105,
    jenis_proyek: 'sanitasi',
    kode_fase: 'perpipaan_luar',
    nama_fase: 'Perpipaan Luar Gedung',
    prioritas: 4,
    overlap_persen: 20,
    durasi_faktor: 1,
    keywords: ['perpipaan luar', 'jaringan pipa', 'pipa dci', 'pipa beton', 'pipa baja'],
    is_active: true,
  },
  {
    id: -106,
    jenis_proyek: 'sanitasi',
    kode_fase: 'aksesoris',
    nama_fase: 'Aksesoris & Valve',
    prioritas: 5,
    overlap_persen: 30,
    durasi_faktor: 0.8,
    keywords: ['aksesoris', 'valve', 'tee', 'reducer', 'bend', 'clamp', 'sambungan'],
    is_active: true,
  },
  {
    id: -107,
    jenis_proyek: 'sanitasi',
    kode_fase: 'testing',
    nama_fase: 'Testing & Commissioning',
    prioritas: 6,
    overlap_persen: 0,
    durasi_faktor: 0.6,
    keywords: ['testing', 'commissioning', 'uji', 'flushing'],
    is_active: true,
  },
  // AIR MINUM
  {
    id: -201,
    jenis_proyek: 'air_minum',
    kode_fase: 'persiapan',
    nama_fase: 'Pekerjaan Persiapan',
    prioritas: 0,
    overlap_persen: 0,
    durasi_faktor: 1,
    keywords: ['persiapan', 'mobilisasi', 'bouwplank', 'pengukuran'],
    is_active: true,
  },
  {
    id: -202,
    jenis_proyek: 'air_minum',
    kode_fase: 'sumber_air',
    nama_fase: 'Pekerjaan Sumber Air',
    prioritas: 1,
    overlap_persen: 0,
    durasi_faktor: 1.2,
    keywords: [
      'pemboran',
      'sumur',
      'mata air',
      'intake',
      'broncaptering',
      'pilot hole',
      'reaming',
      'cassing',
    ],
    is_active: true,
  },
  {
    id: -203,
    jenis_proyek: 'air_minum',
    kode_fase: 'bangunan_penampung',
    nama_fase: 'Bangunan Penampung',
    prioritas: 2,
    overlap_persen: 20,
    durasi_faktor: 1.2,
    keywords: [
      'reservoir',
      'tangki',
      'penampung',
      'ground tank',
      'tower',
      'hidropore',
      'beton',
      'pembesian',
    ],
    is_active: true,
  },
  {
    id: -204,
    jenis_proyek: 'air_minum',
    kode_fase: 'bangunan_pelengkap',
    nama_fase: 'Bangunan Pelengkap',
    prioritas: 3,
    overlap_persen: 25,
    durasi_faktor: 1,
    keywords: ['rumah pompa', 'rumah jaga', 'bangunan bagi', 'bak pelepas'],
    is_active: true,
  },
  {
    id: -205,
    jenis_proyek: 'air_minum',
    kode_fase: 'perpipaan_transmisi',
    nama_fase: 'Perpipaan Transmisi',
    prioritas: 4,
    overlap_persen: 25,
    durasi_faktor: 1.1,
    keywords: ['transmisi', 'pipa pvc', 'pipa gi', 'pipa hdpe', 'galian pipa'],
    is_active: true,
  },
  {
    id: -206,
    jenis_proyek: 'air_minum',
    kode_fase: 'perpipaan_distribusi',
    nama_fase: 'Perpipaan Distribusi',
    prioritas: 5,
    overlap_persen: 30,
    durasi_faktor: 1.1,
    keywords: ['distribusi', 'jaringan', 'reducer', 'tee', 'bend', 'valve', 'gate valve'],
    is_active: true,
  },
  {
    id: -207,
    jenis_proyek: 'air_minum',
    kode_fase: 'sambungan_rumah',
    nama_fase: 'Sambungan Rumah',
    prioritas: 6,
    overlap_persen: 30,
    durasi_faktor: 1,
    keywords: ['sambungan rumah', 'sr', 'water meter', 'kran', 'hidran umum', 'box sr'],
    is_active: true,
  },
  {
    id: -208,
    jenis_proyek: 'air_minum',
    kode_fase: 'testing',
    nama_fase: 'Testing & Commissioning',
    prioritas: 7,
    overlap_persen: 0,
    durasi_faktor: 0.6,
    keywords: ['testing', 'uji', 'flushing', 'desinfeksi'],
    is_active: true,
  },
]

export function defaultFasesForJenis(jenisProyek: string): MasterFasePekerjaan[] {
  const key = jenisProyek === 'air_minum' ? 'air_minum' : 'sanitasi'
  return DEFAULT_MASTER_FASES.filter((f) => f.jenis_proyek === key)
}
